### PR TITLE
Added: detection_box paramter

### PR DESCRIPTION
**Pull request by Owlwasrowk**
According to Issue #24 i implemented the detection_box parameter like i have did in the given snippet of the issue.

### CODE REVIEW

**Review by justinshenk — APPROVED** [review]
Thank you!

**Comment by justinshenk** [comment]
Thank you! Merged

**Comment by Owlwasrowk** [comment]
Is Travis failed check relevant?

**Comment by justinshenk** [comment]
It may have been because I accepted too early. It looks like it passed in master. Thanks again!

**Pull request merged**
