### PR TITLE
Corrected spelling mistake

### PR DESCRIPTION
**Pull request by HabeebRahmanKT**
Corrected a spelling mistake and changed the name of a variable which was previously named with a predefined keyword/method

### CODE REVIEW

**Comment by JustinShenk** [comment]
Thank you!

**Comment by JustinShenk** [comment]
Appears to lead to another error: https://github.com/JustinShenk/fer/actions/runs/8362730645/job/22894032637

**Comment by HabeebRahmanKT** [comment]
Hello. The tests conducted by github seems running fine during the pull request. Just changed one variable name which I felt more suitable other than correcting the spelling. 

Anyway I have changed the variable name back to the previous one. Hopes it will work.

**Comment by HabeebRahmanKT** [comment]
Hello.
I have just made another pull request by just correcting the spelling, but still the test is not running. I am not sure about the error and it's reason since I have just chaged "columsn" to "columns" in a comment.

I really need some help since I am a beginner. Hopes I can fix it with your help.

**Pull request merged**
